-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 15:17:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema readme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema readme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `readme` DEFAULT CHARACTER SET utf8 ;
USE `readme` ;

-- -----------------------------------------------------
-- Table `readme`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registration_date` DATETIME NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `name` VARCHAR(225) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `avatar` VARCHAR(225) NULL,
  `contact_info` VARCHAR(225) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusers_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readme`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_date` DATETIME NOT NULL,
  `title` TEXT(120) NOT NULL,
  `text` TEXT NULL,
  `quote_author` VARCHAR(225) NULL,
  `img_url` VARCHAR(225) NULL,
  `video_url` VARCHAR(225) NULL,
  `users_site_url` VARCHAR(225) NULL,
  `number_of_views` INT NOT NULL DEFAULT 0,
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `users_to_posts_idx` (`users_id` ASC),
  CONSTRAINT `users_to_posts`
    FOREIGN KEY (`users_id`)
    REFERENCES `readme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readme`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_time_of_origin` DATETIME NOT NULL,
  `text` TEXT NOT NULL,
  `users_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_comment_users1_idx` (`users_id` ASC),
  INDEX `fk_comment_post1_idx` (`post_id` ASC),
  CONSTRAINT `users_to_comments`
    FOREIGN KEY (`users_id`)
    REFERENCES `readme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `posts_to_comments`
    FOREIGN KEY (`post_id`)
    REFERENCES `readme`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readme`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_of_origin` DATETIME NOT NULL,
  `text` TEXT NOT NULL,
  `users_id_send` INT NOT NULL,
  `users_id_get` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_message_users1_idx` (`users_id_send` ASC),
  INDEX `fk_messages_users1_idx` (`users_id_get` ASC),
  CONSTRAINT `users_to_messages`
    FOREIGN KEY (`users_id_send`)
    REFERENCES `readme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id_get`)
    REFERENCES `readme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `readme`.`subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`subscribers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NULL DEFAULT NULL,
  `users_subscribe_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_subscribe_users1_idx` (`users_id` ASC, `users_subscribe_id` ASC),
  CONSTRAINT `users_to_subscribers`
    FOREIGN KEY (`users_id`)
    REFERENCES `readme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `readme`.`hashtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`hashtags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `readme`.`content_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`content_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TINYINT NOT NULL,
  `quote` TINYINT NOT NULL,
  `picture` TINYINT NOT NULL,
  `video` TINYINT NOT NULL,
  `url` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `readme`.`posts_hashtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`posts_hashtags` (
  `posts_id` INT NULL DEFAULT NULL,
  `hashtags_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`posts_id`, `hashtags_id`),
  INDEX `fk_posts_has_hashtags_hashtags1_idx` (`hashtags_id` ASC),
  INDEX `fk_posts_has_hashtags_posts1_idx` (`posts_id` ASC),
  CONSTRAINT `fk_posts_has_hashtags_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `readme`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_hashtags_hashtags1`
    FOREIGN KEY (`hashtags_id`)
    REFERENCES `readme`.`hashtags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readme`.`posts_has_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`posts_has_types` (
  `content_types_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`content_types_id`, `posts_id`),
  INDEX `fk_content_types_has_posts_posts1_idx` (`posts_id` ASC),
  INDEX `fk_content_types_has_posts_content_types1_idx` (`content_types_id` ASC),
  CONSTRAINT `fk_content_types_has_posts_content_types1`
    FOREIGN KEY (`content_types_id`)
    REFERENCES `readme`.`content_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_content_types_has_posts_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `readme`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `readme`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `readme`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `likes` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_has_users_users1_idx` (`users_id` ASC),
  INDEX `fk_posts_has_users_posts1_idx` (`posts_id` ASC, `id` ASC),
  UNIQUE INDEX `posts_likes_id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_posts_has_users_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `readme`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `readme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
